[build]
builder = "NIXPACKS"

[deploy]
# run uvicorn from repo root
startCommand = "uvicorn api.server:app --host 0.0.0.0 --port $PORT"

[phases.setup]
# install Python first
nixPkgs = ["python312"]

[phases.install]
# install dependencies from /api/requirements.txt
cmds = ["pip install -r api/requirements.txt"]
